version: '3.9'

x-prod-env-variables: &prod-env-variables
  LOGGER_LEVEL: debug

x-vmm-bot: &vmm-bot-service
  deploy:
    replicas: 1
  env_file:
    - .env
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: 1
  image: vmm-bot:1.0.2
  restart: unless-stopped

services:
  bybit-vmm-bot:
    <<: *vmm-bot-service
    environment:
      <<: *prod-env-variables
      SERVICE_NAME: bybit-vmm-bot
      EXCHANGE_NAME: bybit
      SYMBOL: STOPUSDT
      ORACLE_SYMBOL: STOPUSDT
      INTERVAL_EXECUTION_DURATION: 30s
      NUM_OF_TRADE_ITERATIONS_IN_INTERVAL: 1
      TRADE_AMOUNT_MIN: 60
      TRADE_AMOUNT_MAX: 90
      PRICE_DECIMALS_PRECISION: 5
      AMOUNT_DECIMALS_PRECISION: 0
    build:
      # Note:
      # The image is built only once by running "docker compose build".
      # The image is then referred by other services via the name tag. 
      context: .
      dockerfile: Dockerfile
    container_name: bybit-vmm-bot

  biconomy-vmm-bot:
    <<: *vmm-bot-service
    environment:
      <<: *prod-env-variables
      SERVICE_NAME: biconomy-vmm-bot
      EXCHANGE_NAME: biconomy
      SYMBOL: STOP_USDT
      ORACLE_SYMBOL: STOPUSDT
      INTERVAL_EXECUTION_DURATION: 30s
      NUM_OF_TRADE_ITERATIONS_IN_INTERVAL: 3
      TRADE_AMOUNT_MIN: 1200
      TRADE_AMOUNT_MAX: 1800
      PRICE_DECIMALS_PRECISION: 5
      AMOUNT_DECIMALS_PRECISION: 3
    container_name: biconomy-vmm-bot
