// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplateTraderBackend = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/trade": {
            "post": {
                "description": "Call the trade once method to execute a trade",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Trade once for the configure symbol",
                "operationId": "trade_once",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.TradeOnceOutput"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.errorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "http.errorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "models.TradeOnceOutput": {
            "type": "object"
        }
    }
}`

// SwaggerInfoTraderBackend holds exported Swagger Info so clients can modify it
var SwaggerInfoTraderBackend = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Trader API",
	Description:      "This is a sample server to perform symbol trading requests",
	InfoInstanceName: "TraderBackend",
	SwaggerTemplate:  docTemplateTraderBackend,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfoTraderBackend.InstanceName(), SwaggerInfoTraderBackend)
}
